// Generated by scripts/write-env.mjs from API_URL and TURNSTILE_SITE_KEY. Do not edit or commit.
export const environment = {
  /** Public base URL of the backend API. */
  apiUrl: "https://real-estate-web-1ahe.onrender.com",
  /** Cloudflare Turnstile site key; empty disables the CAPTCHA widget. */
  turnstileSiteKey: "0x4AAAAAAFIFAEn4ALL2_1A0",
} as const;