/**
 * Writes src/environments/environment.ts from environment variables (or a local `.env`).
 *
 * Runs automatically before `npm start`, `npm run build`, `npm run watch` and `npm test`.
 * Only values that are safe to publish belong here: this file is bundled into the browser code.
 * Server-only secrets (INTERNAL_API_KEY) are read at runtime by the SSR server instead.
 */
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';

if (existsSync('.env')) process.loadEnvFile('.env');

// The public Render API is the default for Vercel; API_URL can override it per deployment.
// Other CI builds must still supply API_URL, and local builds use the dev API.
const hosted = Boolean(process.env.VERCEL || process.env.CI);
const vercelApiUrl = process.env.VERCEL ? 'https://real-estate-web-1ahe.onrender.com' : '';
const apiUrl = ((process.env.API_URL ?? '').trim() || vercelApiUrl).replace(/\/+$/, '');

if (!apiUrl && hosted) {
  console.error('API_URL is not set. Set it to the public URL of the backend API, e.g. https://api.example.com');
  process.exit(1);
}

let resolved = apiUrl;
if (!resolved) resolved = 'http://localhost:3000';

if (!URL.canParse(resolved)) {
  console.error(`API_URL is not a valid URL: ${resolved}`);
  process.exit(1);
}

// Cloudflare Turnstile site key (public by design). Empty = no CAPTCHA widget; the API then
// must not require one either (TURNSTILE_SECRET_KEY unset).
// This public widget is registered for the production Vercel hostname. Environment config can
// override it; the matching secret is never included in the website build.
const vercelSiteKey = process.env.VERCEL ? '0x4AAAAAAFIFAEn4ALL2_1A0' : '';
const turnstileSiteKey = (process.env.TURNSTILE_SITE_KEY ?? '').trim() || vercelSiteKey;
const turnstileTestSiteKeys = new Set([
  '1x00000000000000000000AA',
  '2x00000000000000000000AB',
  '1x00000000000000000000BB',
  '2x00000000000000000000BB',
  '3x00000000000000000000FF',
]);
if (turnstileSiteKey && !/^[\w-]{10,100}$/.test(turnstileSiteKey)) {
  console.error('TURNSTILE_SITE_KEY does not look like a Turnstile site key');
  process.exit(1);
}
if (process.env.VERCEL_ENV === 'production' && turnstileTestSiteKeys.has(turnstileSiteKey)) {
  console.error('TURNSTILE_SITE_KEY is a Cloudflare test key; use a real widget site key in production');
  process.exit(1);
}
if (!turnstileSiteKey && hosted) {
  console.warn('TURNSTILE_SITE_KEY is not set: forms are built without a CAPTCHA');
}

mkdirSync('src/environments', { recursive: true });
writeFileSync(
  'src/environments/environment.ts',
  `// Generated by scripts/write-env.mjs from API_URL and TURNSTILE_SITE_KEY. Do not edit or commit.\n` +
    `export const environment = {\n  /** Public base URL of the backend API. */\n  apiUrl: ${JSON.stringify(resolved)},\n` +
    `  /** Cloudflare Turnstile site key; empty disables the CAPTCHA widget. */\n  turnstileSiteKey: ${JSON.stringify(turnstileSiteKey)},\n} as const;\n`,
);
console.log(`environment.ts written (apiUrl: ${resolved}, captcha: ${turnstileSiteKey ? 'on' : 'off'})`);
